micronaut:
  application:
    name: micronaut-crud
datasources:
  default:
    url: jdbc:mysql://mysql:3306/mn_playground?useSSL=false&serverTimezone=UTC
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
flyway:
  datasources:
    default:
      enabled: true