name: Build and Merge

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: my-secret-pw
          MYSQL_DATABASE: mn_playground
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -uroot -pmy-secret-pw" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 3

    env:
      DATASOURCES_DEFAULT_URL: "jdbc:mysql://127.0.0.1:3306/mn_playground?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&autoReconnect=true"
      DATASOURCES_DEFAULT_USERNAME: "root"
      DATASOURCES_DEFAULT_PASSWORD: "my-secret-pw"

    steps:
      - name: Test MySQL Connection
        run: |
          mysql -h 127.0.0.1 -uroot -pmy-secret-pw -e "SHOW DATABASES;" mn_playground

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'
          cache: gradle

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test --scan

      - name: Build application
        run: ./gradlew build

      - name: Merge to main if successful
        if: ${{ success() && github.ref != 'refs/heads/main' }}
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email '<>'
          git fetch --prune --unshallow || true
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "Merging branch '$BRANCH_NAME' into main..."
          git fetch origin main
          git checkout main
          git merge -s recursive -X theirs "$BRANCH_NAME" -m "Auto-merge from $BRANCH_NAME" --allow-unrelated-histories
          git push origin main

      - name: Upload Jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: micronaut-crud-jar
          path: build/libs/*.jar
