name: Build and Merge

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: my-secret-pw
          MYSQL_DATABASE: mn_playground
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -uroot -pmy-secret-pw" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 3

    env:
      DATASOURCES_DEFAULT_URL: "jdbc:mysql://127.0.0.1:3306/mn_playground?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&autoReconnect=true"
      DATASOURCES_DEFAULT_USERNAME: "root"
      DATASOURCES_DEFAULT_PASSWORD: "my-secret-pw"

    steps:
      - name: Test MySQL Connection
        run: |
          mysql -h 127.0.0.1 -uroot -pmy-secret-pw -e "SHOW DATABASES;" mn_playground

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'
          cache: gradle

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test --scan

      - name: Build application
        run: ./gradlew build
